# Collection settings
dT_0: 10 # Path delay through the antennas (ns)
range_start: 4 # One way range at which to start the scan (m)
range_stop: 14 # One way range at which to stop the scan (m)
tx_gain_ind: 63 # Transmit gain index from 0 (lowest) - 63 (highest)
pii: 11 # Pulse integration index from 6 (lowest) - 15 (highest)

# Less used settings
code_channel: 0 # Code channel from 0 - 10; used to deconflict multiple radars
node_id: 1 # Node ID from 1 to (2^32 - 1); avoid 0 and 2^32
persist_flag: 0 # Configuration persistence flag; 0 to not persist, 1 to persist
quick_look_num_scans: 200 # Number of scans to perform in quick-look

# Timing settings
set_config_timeout: 5 # Time (s) allowed to successfully set radar configuration before raising an error
get_config_timeout: 1 # Time (s) allowed to successfully get radar configuration before raising an error
scan_request_timeout: 1 # Time (s) allowed to successfully send scan request before raising error
read_scan_data_timeout: 2 # Time (s) allowed between consecutive packets before raising error
read_residual_timeout: 5 # Time (s) allowed to read residual streaming data before dropping scans
