# Logger configuration
name: &name 'pulson440'
config:
  version: 1
  formatters:
    full:
      format: '%(asctime)s   %(module)-25s   %(levelname)-8s   %(message)s'
    brief:
      format: '%(asctime)s   %(levelname)-8s   %(message)s'
  handlers:
    console:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'brief'
    file:
      class: 'logging.FileHandler'
      level: 'DEBUG'
      formatter: 'full'
      filename: *name
  loggers:
    *name:
      handlers:
        - console
        - file
      level: 'DEBUG' # Effective logging level
